---
# tasks file for jenkins-exporter
- name: Downloading the binary
  get_url:
    url: "{{ url }}"
    dest: /opt/

- name: Installing from binary.
  unarchive:
    src: /opt/jenkins_exporter-1.1.0.tar.gz
    dest: /opt/
    remote_src: yes

- name: Creating service for mysqld_exporter.
  copy:
    src: jenkins_exporter.service
    dest: /etc/systemd/system/
    mode: 0755
    owner: root
  notify: reload systemd

- name: Starting the node_exporter service
  service:
    name: jenkins_exporter
    state: started
